### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by Programmierfreund** [naimo84/node-red-contrib-duplicati#1]
Hi,

I want to create an automated backup scenario for my QNAP-NAS using node-red and duplicati as docker containers. Node-red and duplicati are working fine. I'm using latest docker images in Container Station of QNAP. Unfornately I'm not able to access duplicati via node-red-contrib-duplicati. I have tried serveral possibilites to enter the url in the config node:

http://192.168.xxx.yyyy:8200/login.html
http://192.168.xxx.yyyy:8200/
http://192.168.xxx.yyyy:8200

Anytime I get the following error message via debug node or console: "Error: Request failed with status code 404"

Any ideas?

Best regards

**Comment by naimo84** [comment]
Hi @Programmierfreund ,

currently only http://192.168.xxx.yyyy:8200 is working. I have to implement a trim on the url, alongside with some documentation ;)

The whole duplicati node was only a fun project .... 

I've tested it from my dev computer and also between my two docker container. Both is working without the slash at the end.

Maybe there is some QNAP specfifc firewall? I don't have a QNAP :(

regards,
Benjamin

**Comment by Programmierfreund** [comment]
Hi @naimo84 ,

thanks for your reply. I have tried a lot of url-combinations without success. Therefore I have switched to duplicati-client: https://github.com/Pectojin/duplicati-client.  I'm now invoking duplicati via an exec-node and and the python-based client-scripts that are located in the same container. duplicati is furthermore located in a separate container.

Best regards
Andreas
